# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Dimitrij-Marian Holm"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Dimitrij-Marian Holm"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = ["/static/css","/static/sass","/static/scss","/static/js"] 
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    #title = "Forty"
    #subtitle = "By HTML5 Up"
    menu = "Menu"
    # Optional logo as brand stored in img/
     logo = "logo.png"

    [[params.navigation.links]]
      name = "Main Page"
      url = "#"
	  
	      [[params.navigation.links]]
	  name = "About me"
          url = "/about"

    [[params.navigation.links]]
	  name = "Education"
          url = "/education"
		  
	[[params.navigation.links]]
	  name = "Working Experience"
          url = "/workingexperience"

    [[params.navigation.links]]
      name = "Projects"
      url = "projects"

    [[params.navigation.links]]
      name = "Certificates"
      url = "/certificates"

    [[params.navigation.links]]
      name = "Hobbies"
      url = "hobbies"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Thinker, Tinker, Linker"
    subtitle = "Just three words to describe myself. Of course every human needs more words to be described. If you want to know more about me, feel free to explore my website"
    #buttonText = "Show me"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
  
    [[params.tiles.showcase]]
      title = "About me"
      subtitle = "what am i, what defines me and why am i as i am"
      image = "cv.jpg"
      url = "about"
  
    [[params.tiles.showcase]]
      title = "Education"
      subtitle = "whole education, from apprenticeship to current state"
      image = "education.jpg"
      url = "education"
	  
	  [[params.tiles.showcase]]
      title = "Working Experience"
      subtitle = "Industrial Experience"
      image = "education.jpg"
      url = "workingexperience"
	  
    [[params.tiles.showcase]]
      title = "Hobbies"
      subtitle = "little bit more about myself"
      image = "pic03.jpg"
      url = "hobbies/"

    [[params.tiles.showcase]]
      title = "Certificates"
      subtitle = "all additional education and programmes"
      image = "pic03.jpg"
      url = "/certificates"

    [[params.tiles.showcase]]
      title = "Projects"
      subtitle = "private, research, intership projects and theses"
      image = "pic02.jpg"
      url = "/projects/"



    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = false
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "blogs"


   #Contact section
  [params.contact]
    enable = false
   # buttonSend = "Send message"
   # buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
     formEmail = "dimi1990@gmx.de"

	#Contact Section

    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Dimitrij-M Holm"

    #[[params.footer.social]]
    #  icon = "fa-twitter"
    #  url= "https://www.twitter.com"
    #  label = "Twitter"

    #[[params.footer.social]]
    #  icon = "fa-facebook"
    #  url= "https://www.facebook.com"
    #  label = "Facebook"

    #[[params.footer.social]]
    #  icon = "fa-instagram"
    #  url= "https://www.instagram.com"
    #  label = "Instagram"
    
    #[[params.footer.social]]
    #  icon = "fa-github"
    #  url= "https://www.github.com"
    #  label = "GitHub"

    #[[params.footer.social]]
     # icon = "fa-linkedin"
     # url= "https://www.linkedin.com"
     # label = "LinkedIn"

    #[[params.footer.quicklinks]]
    #  text = "Design: "
   #   url= "https://www.html5up.net"
  #    alt = "HTML5 UP"
